# Generated by Django 5.2.17 on 2026-09-20 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=7)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')], max_length=7)),
                ('session_url', models.URLField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowings.borrowing')),
            ],
        ),
    ]
