services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A library_service worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A library_service beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
